# Generated by Django 3.2.6 on 2021-08-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinima_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Desc', models.TextField()),
                ('Hero', models.CharField(max_length=40)),
                ('Heroin', models.CharField(max_length=30)),
                ('Director', models.CharField(max_length=30)),
                ('Budget', models.CharField(max_length=23)),
                ('poster', models.ImageField(default='alt.png', upload_to='posters')),
            ],
        ),
    ]
